"""Weaviate connection and the passage write path (Story 2.3, AD-2).

Per architecture decision AD-2, this is the sole place a Weaviate client is
constructed and the sole place a Weaviate query is written -- `documents/`
(and any future reader, e.g. Epic 3's chat retrieval) calls `write_passages`
(or a future `search_passages`) rather than importing `weaviate` itself.

Mirrors `session.py`'s lazy-`@lru_cache`-singleton pattern: the client is
built on first use, not at import time, so importing this module never
opens a real network connection on its own (needed for tests, and for
`app.main` importing every route module at startup regardless of whether
Weaviate is configured).
"""

import os
from functools import lru_cache

import weaviate
from weaviate.classes.config import Configure, DataType, Property
from weaviate.classes.data import DataObject
from weaviate.classes.init import Auth
from weaviate.classes.query import Filter
from weaviate.client import WeaviateClient

from app.shared.data_access.shapes import WeaviatePassage

PASSAGE_COLLECTION = "Passage"

# A large document (the 20MB upload cap, thousands of chunks) would
# otherwise go through `insert_many` as one gRPC call carrying every
# object -- both a single oversized request Weaviate may reject outright,
# and a spike in resident memory for the whole batch's text+embedding
# payload at once. Batched insert avoids both; not tuned against a real
# large-document benchmark, just a conservative, documented default.
_INSERT_BATCH_SIZE = 100


@lru_cache
def get_weaviate_client() -> WeaviateClient:
    url = os.environ.get("WEAVIATE_URL")
    api_key = os.environ.get("WEAVIATE_API_KEY")
    if not url or not api_key:
        raise RuntimeError(
            "Missing required environment variable(s): WEAVIATE_URL, WEAVIATE_API_KEY. "
            "See backend/.env.example."
        )
    return weaviate.connect_to_weaviate_cloud(
        cluster_url=url,
        auth_credentials=Auth.api_key(api_key),
    )


def _ensure_passage_collection(client: WeaviateClient) -> None:
    if client.collections.exists(PASSAGE_COLLECTION):
        return
    # vectorizer_config=none: embeddings are computed by the app
    # (shared/embeddings) and supplied on every write, never generated by
    # a Weaviate-side vectorizer module.
    client.collections.create(
        PASSAGE_COLLECTION,
        properties=[
            Property(name="chunk_id", data_type=DataType.TEXT),
            Property(name="document_id", data_type=DataType.TEXT),
            Property(name="user_id", data_type=DataType.TEXT),
            Property(name="chapter", data_type=DataType.TEXT),
            Property(name="chunk_index", data_type=DataType.INT),
            Property(name="text", data_type=DataType.TEXT),
        ],
        vectorizer_config=Configure.Vectorizer.none(),
    )


def write_passages(passages: list[WeaviatePassage]) -> None:
    """The only function `documents/` calls to reach Weaviate (AD-2) -- no
    raw collection/query call may appear anywhere in `documents/`.

    Deletes any existing objects for this batch's `(document_id, user_id)`
    first, then inserts the new batch -- a re-ingest that produces fewer
    chunks than a prior run must not leave orphaned old chunks behind, and
    filtering the delete on `user_id` too (not just `document_id`, which
    alone would already be correct in practice) keeps `shapes.py`'s
    documented rule -- `user_id` required on every write *and* every query
    filter -- true for every Weaviate operation this function performs.

    Requires every passage in `passages` to share the same
    `(document_id, user_id)` pair -- the delete filter is derived from
    `passages[0]` alone, so a mixed batch would silently delete another
    document's (or another user's) passages and insert the new ones under
    whatever `passages[0]` happened to carry. True by construction for
    `documents/service.py`'s only caller today (one document, one owner,
    per `ingest_document` run), but this function is public in `shared/`
    and Epic 3/4 callers won't have that guarantee for free.
    """
    if not passages:
        return

    document_id = passages[0].document_id
    user_id = passages[0].user_id
    if any(p.document_id != document_id or p.user_id != user_id for p in passages):
        raise ValueError(
            "write_passages requires every passage to share the same "
            "(document_id, user_id) -- got a mixed batch."
        )

    client = get_weaviate_client()
    _ensure_passage_collection(client)
    collection = client.collections.get(PASSAGE_COLLECTION)
    collection.data.delete_many(
        where=Filter.by_property("document_id").equal(document_id)
        & Filter.by_property("user_id").equal(user_id)
    )

    for batch_start in range(0, len(passages), _INSERT_BATCH_SIZE):
        batch = passages[batch_start : batch_start + _INSERT_BATCH_SIZE]
        objects = [
            DataObject(
                properties={
                    "chunk_id": p.chunk_id,
                    "document_id": p.document_id,
                    "user_id": p.user_id,
                    "chapter": p.chapter,
                    "chunk_index": p.chunk_index,
                    "text": p.text,
                },
                uuid=p.chunk_id,
                vector=p.embedding,
            )
            for p in batch
        ]
        result = collection.data.insert_many(objects)
        if result.has_errors:
            raise RuntimeError(f"Weaviate write failed: {result.errors}")
