"""Weaviate connection and the passage write path (Story 2.3, AD-2).

Per architecture decision AD-2, this is the sole place a Weaviate client is
constructed and the sole place a Weaviate query is written -- `documents/`
(and any future reader, e.g. Epic 3's chat retrieval) calls `write_passages`
(or a future `search_passages`) rather than importing `weaviate` itself.

Mirrors `session.py`'s lazy-`@lru_cache`-singleton pattern: the client is
built on first use, not at import time, so importing this module never
opens a real network connection on its own (needed for tests, and for
`app.main` importing every route module at startup regardless of whether
Weaviate is configured).
"""

import os
from functools import lru_cache

import weaviate
from weaviate.classes.config import Configure, DataType, Property
from weaviate.classes.data import DataObject
from weaviate.classes.init import Auth
from weaviate.classes.query import Filter
from weaviate.client import WeaviateClient

from app.shared.data_access.shapes import WeaviatePassage

PASSAGE_COLLECTION = "Passage"


@lru_cache
def get_weaviate_client() -> WeaviateClient:
    url = os.environ.get("WEAVIATE_URL")
    api_key = os.environ.get("WEAVIATE_API_KEY")
    if not url or not api_key:
        raise RuntimeError(
            "Missing required environment variable(s): WEAVIATE_URL, WEAVIATE_API_KEY. "
            "See backend/.env.example."
        )
    return weaviate.connect_to_weaviate_cloud(
        cluster_url=url,
        auth_credentials=Auth.api_key(api_key),
    )


def _ensure_passage_collection(client: WeaviateClient) -> None:
    if client.collections.exists(PASSAGE_COLLECTION):
        return
    # vectorizer_config=none: embeddings are computed by the app
    # (shared/embeddings) and supplied on every write, never generated by
    # a Weaviate-side vectorizer module.
    client.collections.create(
        PASSAGE_COLLECTION,
        properties=[
            Property(name="chunk_id", data_type=DataType.TEXT),
            Property(name="document_id", data_type=DataType.TEXT),
            Property(name="user_id", data_type=DataType.TEXT),
            Property(name="chapter", data_type=DataType.TEXT),
            Property(name="chunk_index", data_type=DataType.INT),
            Property(name="text", data_type=DataType.TEXT),
        ],
        vectorizer_config=Configure.Vectorizer.none(),
    )


def write_passages(passages: list[WeaviatePassage]) -> None:
    """The only function `documents/` calls to reach Weaviate (AD-2) -- no
    raw collection/query call may appear anywhere in `documents/`.

    Deletes any existing objects for this batch's `(document_id, user_id)`
    first, then inserts the new batch -- a re-ingest that produces fewer
    chunks than a prior run must not leave orphaned old chunks behind, and
    filtering the delete on `user_id` too (not just `document_id`, which
    alone would already be correct in practice) keeps `shapes.py`'s
    documented rule -- `user_id` required on every write *and* every query
    filter -- true for every Weaviate operation this function performs.
    """
    if not passages:
        return

    client = get_weaviate_client()
    _ensure_passage_collection(client)
    collection = client.collections.get(PASSAGE_COLLECTION)

    document_id = passages[0].document_id
    user_id = passages[0].user_id
    collection.data.delete_many(
        where=Filter.by_property("document_id").equal(document_id)
        & Filter.by_property("user_id").equal(user_id)
    )

    objects = [
        DataObject(
            properties={
                "chunk_id": p.chunk_id,
                "document_id": p.document_id,
                "user_id": p.user_id,
                "chapter": p.chapter,
                "chunk_index": p.chunk_index,
                "text": p.text,
            },
            uuid=p.chunk_id,
            vector=p.embedding,
        )
        for p in passages
    ]
    result = collection.data.insert_many(objects)
    if result.has_errors:
        raise RuntimeError(f"Weaviate write failed: {result.errors}")
